/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author HP-PC
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private JPanel childPanel;
    public Menu1() {
        initComponents();
        labelMenu.setSVGImage("resource/image/home.svg", 40, 40);
        labelMenu.animation();
        svgNV.setSVGImage("resource/image/employee.svg", 40, 40);
        svgRoom.setSVGImage("resource/image/open-door.svg", 40, 40);
        svgKH.setSVGImage("resource/image/people.svg", 40, 40);
        svgDV.setSVGImage("resource/image/waiter.svg", 40, 40);
        svgPay.setSVGImage("resource/image/bill.svg", 40, 40);
        svgTK.setSVGImage("resource/image/description.svg", 40, 40);
        svgPC.setSVGImage("resource/image/delegation.svg", 40, 40);
        svgOut.setSVGImage("resource/image/check-out.svg", 40, 40);
        svgHelp.setSVGImage("resource/image/help.svg",40,40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelMenu = new ui.SVGImage();
        panelNV = new utils.roundedPanel();
        labelNV = new javax.swing.JLabel();
        svgNV = new ui.SVGImage();
        panelRoom = new utils.roundedPanel();
        labelRoom = new javax.swing.JLabel();
        svgRoom = new ui.SVGImage();
        panelKH = new utils.roundedPanel();
        labelKH = new javax.swing.JLabel();
        svgKH = new ui.SVGImage();
        panelDV = new utils.roundedPanel();
        labelDV = new javax.swing.JLabel();
        svgDV = new ui.SVGImage();
        panelPay = new utils.roundedPanel();
        labelPay = new javax.swing.JLabel();
        svgPay = new ui.SVGImage();
        panelTK = new utils.roundedPanel();
        labelTK = new javax.swing.JLabel();
        svgTK = new ui.SVGImage();
        panelPC = new utils.roundedPanel();
        labelPC = new javax.swing.JLabel();
        svgPC = new ui.SVGImage();
        panelOut = new utils.roundedPanel();
        labelOut = new javax.swing.JLabel();
        svgOut = new ui.SVGImage();
        svgHelp = new ui.SVGImage();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new java.awt.CardLayout());
        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 640));

        panelHeader.setBackground(new java.awt.Color(118, 239, 198));
        panelHeader.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                panelHeaderAncestorRemoved(evt);
            }
        });

        labelMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMenuMouseClicked(evt);
            }
        });

        panelNV.setBackground(new java.awt.Color(255, 248, 167));
        panelNV.setRoundedBottomLeft(10);
        panelNV.setRoundedBottomRight(10);
        panelNV.setRoundedTopLeft(10);
        panelNV.setRoundedTopRight(10);
        panelNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNVMouseExited(evt);
            }
        });

        labelNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNV.setText("Nhân Viên");

        javax.swing.GroupLayout panelNVLayout = new javax.swing.GroupLayout(panelNV);
        panelNV.setLayout(panelNVLayout);
        panelNVLayout.setHorizontalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgNV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNVLayout.setVerticalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addComponent(svgNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRoom.setBackground(new java.awt.Color(255, 248, 167));
        panelRoom.setRoundedBottomLeft(10);
        panelRoom.setRoundedBottomRight(10);
        panelRoom.setRoundedTopLeft(10);
        panelRoom.setRoundedTopRight(10);
        panelRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRoomMouseExited(evt);
            }
        });

        labelRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoom.setText("Phòng Hát");

        javax.swing.GroupLayout panelRoomLayout = new javax.swing.GroupLayout(panelRoom);
        panelRoom.setLayout(panelRoomLayout);
        panelRoomLayout.setHorizontalGroup(
            panelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(svgRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRoomLayout.setVerticalGroup(
            panelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRoomLayout.createSequentialGroup()
                        .addComponent(svgRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKH.setBackground(new java.awt.Color(255, 248, 167));
        panelKH.setRoundedBottomLeft(10);
        panelKH.setRoundedBottomRight(10);
        panelKH.setRoundedTopLeft(10);
        panelKH.setRoundedTopRight(10);
        panelKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelKHMouseExited(evt);
            }
        });

        labelKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKH.setText("Khách Hàng");

        javax.swing.GroupLayout panelKHLayout = new javax.swing.GroupLayout(panelKH);
        panelKH.setLayout(panelKHLayout);
        panelKHLayout.setHorizontalGroup(
            panelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKH, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );
        panelKHLayout.setVerticalGroup(
            panelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKHLayout.createSequentialGroup()
                        .addComponent(svgKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelDV.setBackground(new java.awt.Color(255, 248, 167));
        panelDV.setRoundedBottomLeft(10);
        panelDV.setRoundedBottomRight(10);
        panelDV.setRoundedTopLeft(10);
        panelDV.setRoundedTopRight(10);
        panelDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDVMouseExited(evt);
            }
        });

        labelDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDV.setText("Dịch Vụ");

        javax.swing.GroupLayout panelDVLayout = new javax.swing.GroupLayout(panelDV);
        panelDV.setLayout(panelDVLayout);
        panelDVLayout.setHorizontalGroup(
            panelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDVLayout.setVerticalGroup(
            panelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDVLayout.createSequentialGroup()
                        .addComponent(svgDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPay.setBackground(new java.awt.Color(255, 248, 167));
        panelPay.setRoundedBottomLeft(10);
        panelPay.setRoundedBottomRight(10);
        panelPay.setRoundedTopLeft(10);
        panelPay.setRoundedTopRight(10);
        panelPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPayMouseExited(evt);
            }
        });

        labelPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPay.setText("Thanh Toán");

        javax.swing.GroupLayout panelPayLayout = new javax.swing.GroupLayout(panelPay);
        panelPay.setLayout(panelPayLayout);
        panelPayLayout.setHorizontalGroup(
            panelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgPay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPay, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPayLayout.setVerticalGroup(
            panelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPayLayout.createSequentialGroup()
                        .addComponent(svgPay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTK.setBackground(new java.awt.Color(255, 248, 167));
        panelTK.setRoundedBottomLeft(10);
        panelTK.setRoundedBottomRight(10);
        panelTK.setRoundedTopLeft(10);
        panelTK.setRoundedTopRight(10);
        panelTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTKMouseExited(evt);
            }
        });

        labelTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTK.setText("Thống Kê");

        javax.swing.GroupLayout panelTKLayout = new javax.swing.GroupLayout(panelTK);
        panelTK.setLayout(panelTKLayout);
        panelTKLayout.setHorizontalGroup(
            panelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTKLayout.setVerticalGroup(
            panelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTKLayout.createSequentialGroup()
                        .addComponent(svgTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPC.setBackground(new java.awt.Color(255, 248, 167));
        panelPC.setRoundedBottomLeft(10);
        panelPC.setRoundedBottomRight(10);
        panelPC.setRoundedTopLeft(10);
        panelPC.setRoundedTopRight(10);
        panelPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPCMouseExited(evt);
            }
        });

        labelPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPC.setText("Phân Công");

        javax.swing.GroupLayout panelPCLayout = new javax.swing.GroupLayout(panelPC);
        panelPC.setLayout(panelPCLayout);
        panelPCLayout.setHorizontalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgPC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPCLayout.setVerticalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPCLayout.createSequentialGroup()
                        .addComponent(svgPC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelOut.setBackground(new java.awt.Color(255, 248, 167));
        panelOut.setRoundedBottomLeft(10);
        panelOut.setRoundedBottomRight(10);
        panelOut.setRoundedTopLeft(10);
        panelOut.setRoundedTopRight(10);
        panelOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOutMouseExited(evt);
            }
        });

        labelOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOut.setText("Đăng Xuất");

        javax.swing.GroupLayout panelOutLayout = new javax.swing.GroupLayout(panelOut);
        panelOut.setLayout(panelOutLayout);
        panelOutLayout.setHorizontalGroup(
            panelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelOutLayout.setVerticalGroup(
            panelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOutLayout.createSequentialGroup()
                        .addComponent(svgOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(labelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(svgHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(svgHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelHeaderAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelHeaderAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelHeaderAncestorRemoved

    private void labelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuMouseClicked
        setForm(new TrangChu_GUI());
    }//GEN-LAST:event_labelMenuMouseClicked

    private void panelNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNVMouseClicked
        // TODO add your handling code here:
        setForm(new QuanLiNhanVien_GUI());
    }//GEN-LAST:event_panelNVMouseClicked

    private void panelNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNVMouseEntered
        // TODO add your handling code here:
        panelNV.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelNVMouseEntered

    private void panelNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNVMouseExited
        // TODO add your handling code here:
         panelNV.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelNVMouseExited

    private void panelRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRoomMouseEntered
        // TODO add your handling code here:
        panelRoom.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelRoomMouseEntered

    private void panelRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRoomMouseExited
        // TODO add your handling code here:
        panelRoom.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelRoomMouseExited

    private void panelKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKHMouseEntered
        // TODO add your handling code here:
        panelKH.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelKHMouseEntered

    private void panelKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKHMouseExited
        // TODO add your handling code here:
        panelKH.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelKHMouseExited

    private void panelDVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDVMouseEntered
        // TODO add your handling code here:
        panelDV.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelDVMouseEntered

    private void panelDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDVMouseExited
        // TODO add your handling code here:
        panelDV.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelDVMouseExited

    private void panelPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPayMouseEntered
        // TODO add your handling code here:
        panelPay.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelPayMouseEntered

    private void panelPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPayMouseExited
        // TODO add your handling code here:
        panelPay.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelPayMouseExited

    private void panelTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTKMouseEntered
        // TODO add your handling code here:
        panelTK.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelTKMouseEntered

    private void panelTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTKMouseExited
        // TODO add your handling code here:
        panelTK.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelTKMouseExited

    private void panelPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPCMouseEntered
        // TODO add your handling code here:
        panelPC.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelPCMouseEntered

    private void panelPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPCMouseExited
        // TODO add your handling code here:
        panelPC.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelPCMouseExited

    private void panelOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOutMouseEntered
        // TODO add your handling code here:
        panelOut.setBackground(new java.awt.Color(255, 248, 167,95));
    }//GEN-LAST:event_panelOutMouseEntered

    private void panelOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOutMouseExited
        // TODO add your handling code here:
        panelOut.setBackground(new java.awt.Color(255, 248, 167));
    }//GEN-LAST:event_panelOutMouseExited
    
   
  
    private void setForm(JPanel com) {
                childPanel = com;
		mainPanel.removeAll();
		mainPanel.add(childPanel);
                mainPanel.repaint();
		mainPanel.revalidate();       
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDV;
    private javax.swing.JLabel labelKH;
    private ui.SVGImage labelMenu;
    private javax.swing.JLabel labelNV;
    private javax.swing.JLabel labelOut;
    private javax.swing.JLabel labelPC;
    private javax.swing.JLabel labelPay;
    private javax.swing.JLabel labelRoom;
    private javax.swing.JLabel labelTK;
    private javax.swing.JPanel mainPanel;
    private utils.roundedPanel panelDV;
    private javax.swing.JPanel panelHeader;
    private utils.roundedPanel panelKH;
    private utils.roundedPanel panelNV;
    private utils.roundedPanel panelOut;
    private utils.roundedPanel panelPC;
    private utils.roundedPanel panelPay;
    private utils.roundedPanel panelRoom;
    private utils.roundedPanel panelTK;
    private ui.SVGImage svgDV;
    private ui.SVGImage svgHelp;
    private ui.SVGImage svgKH;
    private ui.SVGImage svgNV;
    private ui.SVGImage svgOut;
    private ui.SVGImage svgPC;
    private ui.SVGImage svgPay;
    private ui.SVGImage svgRoom;
    private ui.SVGImage svgTK;
    // End of variables declaration//GEN-END:variables
}
