/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import utils.Utils;

/**
 *
 * @author HP-PC
 */
public class TrangChu_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu_GUI
     */
    public TrangChu_GUI() {
//        setBounds(0, 0, Utils.getScreenWidth(), Utils.getBodyHeight());
//		JLabel lblBackground = new JLabel("");
//		lblBackground.setIcon(Utils.getImageIcon("Rectangle1.png"));
//		//lblBackground.setBounds(0, 0, Utils.getScreenWidth(), Utils.getBodyHeight());
//		this.add(lblBackground);
//                this.setLayout(new BorderLayout());
    initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 660));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP-PC\\OneDrive\\OneDrive - Industrial University of HoChiMinh City\\Nam_2\\HK2\\JavaSwing\\Project\\NhomX_DeTai4_PTUD\\Hinh\\Rectangle1.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
